name: Test all
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test-all:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.18'
      - run: go vet ./...
      - run: go test ./...